### ISSUE TITLE
Timestamp and Hourly Forecast Time Incorrect

### ISSUE THREAD

**Issue by cbarham84** [mawinkler/astroweather-card#16]
Just downloaded the integration as well as this custom card. When creating the card I noticed the forecast time was off by about 3 hours or so. Time zone is correct in configuration as well as my home assistant instance.
![image](https://github.com/mawinkler/astroweather-card/assets/20057099/7a926398-effb-4bfe-90d9-d493d9259f81)
![image](https://github.com/mawinkler/astroweather-card/assets/20057099/69f15b16-3b19-47b8-a320-d25418c49e39)
![image](https://github.com/mawinkler/astroweather-card/assets/20057099/af37ee36-d910-414d-a6f9-0392a214bb05)
 
Any help appreciated. Thanks!

**Comment by mawinkler** [comment]
Hi Chris,
this timestamp refers to the start time of the forecast data being used. Met.no is hourly, but 7timer has a resolution of 3hrs only. Since I'm merging the data of both the timestamp "jumps" in 3hs steps.
The only source for seeing and transparency I'm aware of (with a free API) is 7timer. Met.no does not provide these measurements.
